In [2]:
import torch

torch.__version__

'1.2.0'

In [3]:
x = torch.empty(4, 4)
x

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
x = torch.rand(4, 4)
x

tensor([[0.4571, 0.6534, 0.6567, 0.7448],
        [0.7982, 0.2719, 0.1462, 0.1002],
        [0.4844, 0.2471, 0.1718, 0.4610],
        [0.1248, 0.2392, 0.0900, 0.8317]])

In [6]:
x = torch.zeros(4, 4, dtype=torch.long)
x

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [7]:
x = torch.tensor([3, 3])
x

tensor([3, 3])

In [12]:
x = x.new_ones(5, 3, dtype=torch.float16)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [14]:
x = torch.randn_like(x, dtype=torch.float32)
x

tensor([[ 6.1966e-02, -6.8877e-01,  1.1914e+00],
        [-6.0726e-01, -1.2968e+00, -3.8298e-01],
        [ 4.8065e-01, -1.7426e+00,  1.2192e+00],
        [ 7.1235e-01, -1.8793e-04,  4.9776e-01],
        [-7.0959e-01,  4.2181e-01, -1.3299e+00]])

In [15]:
x.size()

torch.Size([5, 3])

In [16]:
y = torch.rand(5, 3)
x + y

tensor([[ 0.7378,  0.0989,  1.6823],
        [-0.4888, -0.3598,  0.5000],
        [ 0.9713, -1.6639,  1.2789],
        [ 1.6718,  0.0588,  1.3338],
        [-0.0920,  1.3448, -0.4208]])

In [17]:
torch.add(x, y)

tensor([[ 0.7378,  0.0989,  1.6823],
        [-0.4888, -0.3598,  0.5000],
        [ 0.9713, -1.6639,  1.2789],
        [ 1.6718,  0.0588,  1.3338],
        [-0.0920,  1.3448, -0.4208]])

In [21]:
result = torch.empty(1, 2)
torch.add(x, y, out=result)
result

tensor([[ 0.7378,  0.0989,  1.6823],
        [-0.4888, -0.3598,  0.5000],
        [ 0.9713, -1.6639,  1.2789],
        [ 1.6718,  0.0588,  1.3338],
        [-0.0920,  1.3448, -0.4208]])

In [22]:
y.add_(x)
y

tensor([[ 0.7378,  0.0989,  1.6823],
        [-0.4888, -0.3598,  0.5000],
        [ 0.9713, -1.6639,  1.2789],
        [ 1.6718,  0.0588,  1.3338],
        [-0.0920,  1.3448, -0.4208]])

In [23]:
x[:, 1]

tensor([-6.8877e-01, -1.2968e+00, -1.7426e+00, -1.8793e-04,  4.2181e-01])

In [26]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(2, 8)
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [27]:
x = torch.randn(1)
x.item()

-0.6415746212005615

In [28]:
a = torch.randn(5)
a.numpy()

array([ 1.8280909 , -1.1979488 ,  0.5889133 ,  0.00288627, -0.7670562 ],
      dtype=float32)

In [29]:
a.add_(1)

tensor([ 2.8281, -0.1979,  1.5889,  1.0029,  0.2329])

In [32]:
import numpy as np

a = np.random.randn(4, 4)
b = torch.from_numpy(a)
b

tensor([[ 1.2791,  0.7384, -0.6751, -1.2753],
        [-0.4217, -0.0486,  0.9324, -0.5737],
        [ 0.9238,  0.1002,  1.0417, -0.0244],
        [-0.0638, -0.2855, -0.7293, -0.0151]], dtype=torch.float64)

In [33]:
torch.cuda.is_available()

False

In [36]:
cpu = torch.device('cpu')
b.to(cpu)

tensor([[ 1.2791,  0.7384, -0.6751, -1.2753],
        [-0.4217, -0.0486,  0.9324, -0.5737],
        [ 0.9238,  0.1002,  1.0417, -0.0244],
        [-0.0638, -0.2855, -0.7293, -0.0151]], dtype=torch.float64)

In [39]:
b.to('cpu')

tensor([[ 1.2791,  0.7384, -0.6751, -1.2753],
        [-0.4217, -0.0486,  0.9324, -0.5737],
        [ 0.9238,  0.1002,  1.0417, -0.0244],
        [-0.0638, -0.2855, -0.7293, -0.0151]], dtype=torch.float64)

In [38]:
b.to(dtype=torch.int)

tensor([[ 1.2791,  0.7384, -0.6751, -1.2753],
        [-0.4217, -0.0486,  0.9324, -0.5737],
        [ 0.9238,  0.1002,  1.0417, -0.0244],
        [-0.0638, -0.2855, -0.7293, -0.0151]], dtype=torch.float64)