In [18]:
import torch

In [19]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [20]:
y = x + x
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [21]:
z = y * y * 3
out = z.mean()
z, out

(tensor([[12., 12.],
         [12., 12.]], grad_fn=<MulBackward0>),
 tensor(12., grad_fn=<MeanBackward0>))

In [22]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
a.requires_grad

False

In [23]:
a.requires_grad_(True)
a.requires_grad

True

In [24]:
b = (a * a).sum()

In [25]:
out.backward()

In [26]:
x.grad

tensor([[6., 6.],
        [6., 6.]])

In [34]:
x = torch.randn([3, 2], requires_grad=True)

y = x * 2

while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([[ -33.0804,  160.1888],
        [-402.1503,  388.7195],
        [-144.0759, -938.9174]], grad_fn=<MulBackward0>)


In [36]:
# grads = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)
grads = torch.ones(3, 2)
y.backward(grads)

x.grad

tensor([[512., 512.],
        [512., 512.],
        [512., 512.]])

In [37]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
